### ISSUE TITLE
Invalid mapping...

### ISSUE THREAD

**Issue by kitplummer** [nknapp/customize-engine-less#1]
``` sh
Loading bootprint-openapi 0.16.0
Loading bootprint-json-schema 0.8.6
Loading bootprint-base 0.7.2

/usr/local/lib/node_modules/bootprint/node_modules/q/q.js:155
                throw e;
                ^
Error: Invalid mapping: {"generated":{"line":5,"column":17487},"source":"/usr/local/lib/node_modules/bootprint-openapi/node_modules/bootstrap/less/type.less","original":{"line":1,"column":null},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/usr/local/lib/node_modules/bootprint/node_modules/less/node_modules/source-map/lib/source-map-generator.js:277:13)
    at SourceMapGenerator_addMapping [as addMapping] (/usr/local/lib/node_modules/bootprint/node_modules/less/node_modules/source-map/lib/source-map-generator.js:101:12)
    at SourceMapOutput.add (/usr/local/lib/node_modules/bootprint/node_modules/less/lib/less/source-map-output.js:88:42)
    at Element.genCSS (/usr/local/lib/node_modules/bootprint/node_modules/less/lib/less/tree/element.js:42:12)
    at Selector.genCSS (/usr/local/lib/node_modules/bootprint/node_modules/less/lib/less/tree/selector.js:104:21)
    at Ruleset.genCSS (/usr/local/lib/node_modules/bootprint/node_modules/less/lib/less/tree/ruleset.js:389:21)
    at Directive.outputRuleset (/usr/local/lib/node_modules/bootprint/node_modules/less/lib/less/tree/directive.js:111:22)
    at Media.genCSS (/usr/local/lib/node_modules/bootprint/node_modules/less/lib/less/tree/media.js:34:10)
    at Ruleset.genCSS (/usr/local/lib/node_modules/bootprint/node_modules/less/lib/less/tree/ruleset.js:414:18)
    at SourceMapOutput.toCSS (/usr/local/lib/node_modules/bootprint/node_modules/less/lib/less/source-map-output.js:126:24)
```

Appears to be an issue with the 2.7.0 release of `less`.

https://laracasts.com/discuss/channels/elixir/elixir-ccompilation-fails-on-new-page

**Comment by nknapp** [comment]
Appearently this is due to https://github.com/less/less.js/issues/2896 
I'll change the dependencies to use a ~2.6 version

**Comment by matthew-dean** [comment]
Sorry about that. 2.7.0 has been unpublished and 2.7.1 is published.

**Comment by nknapp** [comment]
Thanks for the personal notice. And thanks for fixing so quickly.

**Comment by kitplummer** [comment]
Thanks @matthew-dean and @nknapp - confirmed, we're all good.

**Comment by matthew-dean** [comment]
👍
